source_shares = {
"BHP" : "BHP Group Ltd",
"CBA" : "Commonwealth Bank of Australia",
"CSL" : "CSL Ltd",
"NAB" : "National Australia Bank Ltd",
"WBC" : "Westpac Banking Corporation",
"MQG" : "Macquarie Group Ltd",
"WDS" : "Woodside Energy Group Ltd",
"ANZ" : "Australia and New Zealand Banking Group Ltd",
"FMG" : "Fortescue Metals Group Ltd",
"WES" : "Wesfarmers Ltd",
"TLS" : "Telstra Corporation Ltd",
"WOW" : "Woolworths Group Ltd",
"TCL" : "Transurban Group",
"GMG" : "Goodman Group",
"RIO" : "RIO Tinto Ltd",
"STO" : "Santos Ltd",
"COL" : "Coles Group Ltd",
"ALL" : "Aristocrat Leisure Ltd",
"S32" : "SOUTH32 Ltd",
"WTC" : "Wisetech Global Ltd",
"QBE" : "QBE Insurance Group Ltd",
"BXB" : "Brambles Ltd",
"SHL" : "Sonic Healthcare Ltd",
"REA" : "REA Group Ltd",
"RHC" : "Ramsay Health Care Ltd",
"NCM" : "Newcrest Mining Ltd",
"ASX" : "ASX Ltd",
"JHX" : "James Hardie Industries Plc",
"CPU" : "Computershare Ltd",
"SCG" : "Scentre Group",
"COH" : "Cochlear Ltd",
"SUN" : "Suncorp Group Ltd",
"RMD" : "Resmed Inc",
"APA" : "APA Group",
"EDV" : "Endeavour Group Ltd",
"XRO" : "Xero Ltd",
"AMC" : "Amcor Plc",
"MIN" : "Mineral Resources Ltd",
"VAS" : "Vanguard Australian Shares INDEX ETF",
"IAG" : "Insurance Australia Group Ltd",
"ORG" : "Origin Energy Ltd",
"FPH" : "Fisher & Paykel Healthcare Corporation Ltd",
"REH" : "Reece Ltd",
"TPG" : "TPG Telecom Ltd",
"PLS" : "Pilbara Minerals Ltd",
"MPL" : "Medibank Private Ltd",
"AIA" : "Auckland International Airport Ltd",
"TLC" : "The Lottery Corporation Ltd",
"TWE" : "Treasury Wine Estates Ltd",
"MGOC" : "Magellan Global Fund (Open Class) (Managed Fund)",
"IGO" : "IGO Ltd",
"AFI" : "Australian Foundation Investment Company Ltd",
"SOL" : "Washington H Soul Pattinson & Company Ltd",
"DXS" : "Dexus",
"SPK" : "Spark New Zealand Ltd",
"AKE" : "Allkem Ltd",
"NST" : "Northern Star Resources Ltd",
"OZL" : "OZ Minerals Ltd",
"SGP" : "Stockland",
"QAN" : "Qantas Airways Ltd",
"VCX" : "Vicinity Centres",
"MGR" : "Mirvac Group",
"ALD" : "Ampol Ltd",
"PMGOLD" : "Gold Corporation",
"LYC" : "Lynas Rare EARTHS Ltd",
"GPT" : "GPT Group",
"BSL" : "Bluescope Steel Ltd",
"WOR" : "Worley Ltd",
"MCY" : "Mercury NZ Ltd",
"CAR" : "Carsales.com Ltd",
"YAL" : "Yancoal Australia Ltd",
"SEK" : "Seek Ltd",
"ALX" : "Atlas Arteria",
"IPL" : "Incitec Pivot Ltd",
"WHC" : "Whitehaven Coal Ltd",
"IEL" : "Idp Education Ltd",
"ARG" : "Argo Investments Ltd",
"LLC" : "Lendlease Group",
"ORI" : "Orica Ltd",
"AZJ" : "Aurizon Holdings Ltd",
"SVW" : "Seven Group Holdings Ltd",
"EBO" : "Ebos Group Ltd",
"DMP" : "Domino's PIZZA Enterprises Ltd",
"MEZ" : "Meridian Energy Ltd",
"IFT" : "Infratil Ltd",
"CHC" : "Charter Hall Group",
"ALQ" : "Als Ltd",
"CWY" : "Cleanaway Waste Management Ltd",
"HVN" : "Harvey Norman Holdings Ltd",
"PME" : "Pro Medicus Ltd",
"AGL" : "AGL Energy Ltd",
"SDF" : "Steadfast Group Ltd",
"IVV" : "Ishares S&P 500 ETF",
"BEN" : "Bendigo and Adelaide Bank Ltd",
"NXT" : "NEXTDC Ltd",
"ALU" : "Altium Ltd",
"GQG" : "GQG Partners Inc",
"JBH" : "JB Hi-Fi Ltd",
"QUB" : "QUBE Holdings Ltd",
"VGS" : "Vanguard MSCI INDEX International Shares ETF",
"STW" : "SPDR S&P/ASX 200 Fund",
"IOZ" : "Ishares Core S&P/ASX 200 ETF",
"EVN" : "Evolution Mining Ltd",
"AWC" : "Alumina Ltd",
"BOQ" : "Bank of Queensland Ltd",
"CGF" : "Challenger Ltd",
"ILU" : "Iluka Resources Ltd",
"VEA" : "Viva Energy Group Ltd",
"NHC" : "New Hope Corporation Ltd",
"FBU" : "Fletcher Building Ltd",
"MTS" : "Metcash Ltd",
"SQ2" : "Block Inc",
"BPT" : "Beach Energy Ltd",
"TNE" : "Technology One Ltd",
"LTR" : "Liontown Resources Ltd",
"NHF" : "Nib Holdings Ltd",
"AMP" : "AMP Ltd",
"A2M" : "The a2 Milk Company Ltd",
"DOW" : "Downer Edi Ltd",
"FLT" : "Flight Centre Travel Group Ltd",
"ANN" : "Ansell Ltd",
"APE" : "Eagers Automotive Ltd",
"NWL" : "Netwealth Group Ltd",
"NEC" : "Nine Entertainment Co. Holdings Ltd",
"PMV" : "Premier Investments Ltd",
"BLD" : "Boral Ltd",
"CLW" : "Charter Hall Long Wale REIT",
"RWC" : "Reliance Worldwide Corporation Ltd",
"CNU" : "Chorus Ltd",
"BKW" : "Brickworks Ltd",
"CRN" : "Coronado Global Resources Inc",
"CBAPD" : "Commonwealth Bank of Australia",
"APM" : "APM Human Services International Ltd",
"VTS" : "Vanguard US Total Market Shares INDEX ETF",
"BRG" : "Breville Group Ltd",
"SCP" : "Shopping Centres Australasia Property Group",
"SGM" : "Sims Ltd",
"NIC" : "Nickel Industries Ltd",
"ORA" : "Orora Ltd",
"ZIM" : "Zimplats Holdings Ltd",
"NSR" : "National Storage REIT",
"QUAL" : "Vaneck MSCI International Quality ETF",
"GNE" : "Genesis Energy Ltd",
"CIA" : "Champion Iron Ltd",
"AVZ" : "AVZ Minerals Ltd",
"CTD" : "Corporate Travel Management Ltd",
"GOZ" : "Growthpoint Properties Australia",
"SGR" : "The Star Entertainment Group Ltd",
"HDN" : "Homeco Daily Needs REIT",
"BWP" : "BWP Trust",
"GOLD" : "ETFs Metal Securities Australia Ltd",
"IOO" : "Ishares Global 100 ETF",
"PXA" : "Pexa Group Ltd",
"ARB" : "ARB Corporation Ltd",
"NDQ" : "Betashares Nasdaq 100 ETF",
"EVT" : "Event Hospitality and Entertainment Ltd",
"NABPH" : "National Australia Bank Ltd",
"MFG" : "Magellan Financial Group Ltd",
"CXO" : "Core Lithium Ltd",
"DRR" : "Deterra Royalties Ltd",
"SYA" : "Sayona Mining Ltd",
"ABP" : "Abacus Property Group",
"SNZ" : "Summerset Group Holdings Ltd",
"CQR" : "Charter Hall Retail REIT",
"VNT" : "Ventia Services Group Ltd",
"SUL" : "Super Retail Group Ltd",
"VHY" : "Vanguard Australian Shares High Yield ETF",
"A200" : "Betashares Australia 200 ETF",
"BFL" : "BSP Financial Group Ltd",
"BAP" : "Bapcor Ltd",
"CSR" : "CSR Ltd",
"LNK" : "Link Administration Holdings Ltd",
"PRU" : "Perseus Mining Ltd",
"PDN" : "Paladin Energy Ltd",
"DHG" : "Domain Holdings Australia Ltd",
"VEU" : "Vanguard All-World Ex-US Shares INDEX ETF",
"HLS" : "Healius Ltd",
"VAP" : "Vanguard Australian Property Securities INDEX ETF",
"SMR" : "Stanmore Resources Ltd",
"PNI" : "Pinnacle Investment Management Group Ltd",
"TAH" : "Tabcorp Holdings Ltd",
"MGF" : "Magellan Global Fund",
"IPH" : "IPH Ltd",
"ETHI" : "Betashares Global Sustainability Leaders ETF",
"IRE" : "Iress Ltd",
"IFL" : "Insignia Financial Ltd",
"CMW" : "Cromwell Property Group",
"HUB" : "HUB24 Ltd",
"SKC" : "Skycity Entertainment Group Ltd",
"TLX" : "TELIX Pharmaceuticals Ltd",
"AIZ" : "Air New Zealand Ltd",
"DDR" : "Dicker Data Ltd",
"NABPI" : "National Australia Bank Ltd",
"LOV" : "Lovisa Holdings Ltd",
"AUB" : "AUB Group Ltd",
"VUK" : "Virgin Money Uk Plc",
"WAM" : "WAM Capital Ltd",
"SFR" : "Sandfire Resources Ltd",
"NABPF" : "National Australia Bank Ltd",
"JLG" : "Johns LYNG Group Ltd",
"NUF" : "Nufarm Ltd",
"WEB" : "Webjet Ltd",
"HYGG" : "Hyperion GBL Growth Companies Fund (Managed Fund)",
"INA" : "Ingenia Communities Group",
"CIP" : "Centuria Industrial REIT",
"GNC" : "Graincorp Ltd",
"PDL" : "Pendal Group Ltd",
"HBRD" : "Betashares Active Australian Hybrids Fund (Managed Fund)",
"AAA" : "Betashares Australian High Interest Cash ETF",
"WPR" : "Waypoint REIT",
"ELD" : "Elders Ltd",
"VGAD" : "Vanguard MSCI INDEX International Shares (Hedged) ETF",
"LIC" : "Lifestyle Communities Ltd",
"WBCPJ" : "Westpac Banking Corporation",
"VDHG" : "Vanguard Diversified High Growth INDEX ETF",
"WBCPK" : "Westpac Banking Corporation",
"MXT" : "Metrics Master Income Trust",
"CEN" : "Contact Energy Ltd",
"CBAPK" : "Commonwealth Bank of Australia",
"WBCPH" : "Westpac Banking Corporation",
"PPT" : "Perpetual Ltd",
"IAF" : "Ishares Core Composite Bond ETF",
"LKE" : "Lake Resources N.L.",
"ANZPG" : "Australia and New Zealand Banking Group Ltd",
"MVW" : "Vaneck Australian EQUAL Weight ETF",
"PSI" : "PSC Insurance Group Ltd",
"CBAPI" : "Commonwealth Bank of Australia",
"CBAPH" : "Commonwealth Bank of Australia",
"GRR" : "Grange Resources Ltd",
"CHN" : "Chalice Mining Ltd",
"BRN" : "Brainchip Holdings Ltd",
"OCL" : "Objective Corporation Ltd",
"IVC" : "Invocare Ltd",
"WLE" : "Wam Leaders Ltd",
"HMC" : "Home Consortium Ltd",
"RBD" : "Restaurant Brands New Zealand Ltd",
"WBCPL" : "Westpac Banking Corporation",
"LSF" : "L1 Long Short Fund Ltd",
"MAQ" : "Macquarie Telecom Group Ltd",
"ANZPI" : "Australia and New Zealand Banking Group Ltd",
"LFS" : "Latitude Group Holdings Ltd",
"NABPD" : "National Australia Bank Ltd",
"MFF" : "MFF Capital Investments Ltd",
"ARF" : "Arena REIT",
"WBCPI" : "Westpac Banking Corporation",
"CNI" : "Centuria Capital Group",
"IMU" : "Imugene Ltd",
"ABC" : "Adbri Ltd",
"CMM" : "Capricorn Metals Ltd",
"VAF" : "Vanguard Australian Fixed Interest INDEX ETF",
"INR" : "Ioneer Ltd",
"GOR" : "Gold Road Resources Ltd",
"CBAPG" : "Commonwealth Bank of Australia",
"KLS" : "Kelsian Group Ltd",
"WAF" : "West African Resources Ltd",
"LFG" : "Liberty Financial Group",
"CCP" : "Credit Corp Group Ltd",
"CQE" : "Charter Hall Social Infrastructure REIT",
"JDO" : "Judo Capital Holdings Ltd",
"PPH" : "Pushpay Holdings Ltd",
"BKL" : "Blackmores Ltd",
"NAN" : "Nanosonics Ltd",
"DEG" : "De Grey Mining Ltd",
"PNV" : "Polynovo Ltd",
"CDA" : "Codan Ltd",
"RCAP" : "Resolution Cap Global Prop Sec (Managed Fund)",
"ANZPJ" : "Australia and New Zealand Banking Group Ltd",
"BKI" : "BKI Investment Company Ltd",
"MP1" : "Megaport Ltd",
"CGC" : "Costa Group Holdings Ltd",
"MGH" : "Maas Group Holdings Ltd",
"SLR" : "Silver Lake Resources Ltd",
"FAIR" : "Betashares Australian Sustainability Leaders ETF",
"AUI" : "Australian United Investment Company Ltd",
"GUD" : "G.U.D. Holdings Ltd",
"RRL" : "Regis Resources Ltd",
"CBAPJ" : "Commonwealth Bank of Australia",
"MND" : "Monadelphous Group Ltd",
"SP1" : "Southern Cross Payments Ltd",
"OBL" : "Omni Bridgeway Ltd",
"VUL" : "Vulcan Energy Resources Ltd",
"NVX" : "Novonix Ltd",
"CKF" : "Collins Foods Ltd",
"IXJ" : "Ishares Global Healthcare ETF",
"CXL" : "CALIX Ltd",
"BGP" : "Briscoe Group Australasia Ltd",
"TGR" : "Tassal Group Ltd",
"BGA" : "Bega Cheese Ltd",
"AAC" : "Australian Agricultural Company Ltd",
"NWS" : "News Corporation",
"GMA" : "Genworth Mortgage Insurance Australia Ltd",
"NEA" : "Nearmap Ltd",
"VSL" : "Vulcan Steel Ltd",
"DBI" : "Dalrymple Bay Infrastructure Ltd",
"MAF" : "Ma Financial Group Ltd",
"PBH" : "Pointsbet Holdings Ltd",
"PTM" : "Platinum Asset Management Ltd",
"KAR" : "Karoon Energy Ltd",
"SYR" : "Syrah Resources Ltd",
"NWH" : "NRW Holdings Ltd",
"SDR" : "Siteminder Ltd",
"MQGPC" : "Macquarie Group Ltd",
"UMG" : "United Malt Group Ltd",
"DUI" : "Diversified United Investment Ltd",
"MCR" : "Mincor Resources NL",
"HTA" : "Hutchison Telecommunications (Australia) Ltd",
"HGH" : "Heartland Group Holdings Ltd",
"ANZPF" : "Australia and New Zealand Banking Group Ltd",
"MMS" : "Mcmillan Shakespeare Ltd",
"HSN" : "Hansen Technologies Ltd",
"RFF" : "Rural Funds Group",
"ANZPH" : "Australia and New Zealand Banking Group Ltd",
"COF" : "Centuria Office REIT",
"ING" : "Inghams Group Ltd",
"DTL" : "Data#3 Ltd",
"MQGPD" : "Macquarie Group Ltd",
"NABPE" : "National Australia Bank Ltd",
"ASB" : "Austal Ltd",
"360" : "LIFE360 Inc",
"SIQ" : "Smartgroup Corporation Ltd",
"PWH" : "PWR Holdings Ltd",
"29M" : "29METALS Ltd",
"ERA" : "Energy Resources of Australia Ltd",
"MICH" : "Magellan Infrastructure Fund (Currency Hedged)(Managed Fund)",
"AX1" : "Accent Group Ltd",
"NCK" : "Nick Scali Ltd",
"CUV" : "Clinuvel Pharmaceuticals Ltd",
"JIN" : "Jumbo Interactive Ltd",
"BOE" : "Boss Energy Ltd",
"DXI" : "Dexus Industria REIT",
"XARO" : "Activex Ardea Real Outcome Bond Fund (Managed Fund)",
"ACL" : "Australian Clinical Labs Ltd",
"OML" : "Ooh!Media Ltd",
"SGF" : "SG Fleet Group Ltd",
"GEM" : "G8 Education Ltd",
"CIN" : "Carlton Investments Ltd",
"BGL" : "Bellevue Gold Ltd",
"IEM" : "Ishares MSCI Emerging Markets ETF",
"NMT" : "Neometals Ltd",
"TER" : "Terracom Ltd",
"IMD" : "IMDEX Ltd",
"RMS" : "Ramelius Resources Ltd",
"IEU" : "Ishares Europe ETF",
"SBM" : "ST Barbara Ltd",
"WTN" : "Winton Land Ltd",
"DGL" : "DGL Group Ltd",
"SWM" : "Seven West Media Ltd",
"JRV" : "Jervois Global Ltd",
"MQGPF" : "Macquarie Group Ltd",
"KKC" : "KKR Credit Income Fund",
"ABB" : "Aussie Broadband Ltd",
"SFY" : "SPDR S&P/ASX 50 Fund",
"IFRA" : "Vaneck Ftse Global Infrastructure (Hedged) ETF",
"MQGPE" : "Macquarie Group Ltd",
"AEF" : "Australian Ethical Investment Ltd",
"SIG" : "Sigma Healthcare Ltd",
"IDX" : "Integral Diagnostics Ltd",
"ECX" : "Eclipx Group Ltd",
"KMD" : "KMD Brands Ltd",
"TUA" : "Tuas Ltd",
"NEU" : "Neuren Pharmaceuticals Ltd",
"VSO" : "Vanguard MSCI Australian Small Companies INDEX ETF",
"WGB" : "Wam Global Ltd",
"MBLPC" : "Macquarie Bank Ltd",
"EMR" : "Emerald Resources NL",
"SLX" : "SILEX Systems Ltd",
"URW" : "Unibail-Rodamco-Westfield",
'PL8' : 'Plato Income Maximiser Ltd',
'DJW' : 'Djerriwarrh Investments Ltd',
'NBI' : 'NB Global Corporate Income Trust',
'VGB' : 'Vanguard Australian Government Bond INDEX ETF',
'HACK' : 'Betashares Global Cybersecurity ETF',
'ZIP' : 'ZIP Co Ltd',
'PPM' : 'Pepper Money Ltd',
'SM1' : 'Synlait Milk Ltd',
'IAA' : 'Ishares Asia 50 ETF',
'OFX' : 'OFX Group Ltd',
'BLY' : 'Boart Longyear Group Ltd',
'OCA' : 'Oceania Healthcare Ltd',
'MBLPD' : 'Macquarie Bank Ltd',
'JHG' : 'Janus Henderson Group Plc',
'AD8' : 'Audinate Group Ltd',
'VESG' : 'Vanguard Ethically Conscious International Shares INDEX ETF',
'HPI' : 'Hotel Property Investments',
'QAL' : 'Qualitas Ltd',
'RPL' : 'Regal Partners Ltd',
'NNUK' : 'Nanuk New World Fund (Managed Fund)',
'MSB' : 'Mesoblast Ltd',
'MAD' : 'Mader Group Ltd',
'VIF' : 'Vanguard International Fixed Interest INDEX (Hedged) ETF',
'RED' : 'RED 5 Ltd',
'REG' : 'Regis Healthcare Ltd',
'WBCPE' : 'Westpac Banking Corporation',
'PGF' : 'PM Capital Global Opportunities Fund Ltd',
'MVA' : 'Vaneck Australian Property ETF',
'BBN' : 'Baby Bunting Group Ltd',
'COE' : 'Cooper Energy Ltd',
'VDBA' : 'Vanguard Diversified Balanced INDEX ETF',
'VDGR' : 'Vanguard Diversified Growth INDEX ETF',
'TPW' : 'Temple & Webster Group Ltd',
'IHVV' : 'Ishares S&P 500 Aud Hedged ETF',
'RIC' : 'Ridley Corporation Ltd',
'VGE' : 'Vanguard Ftse Emerging Markets Shares ETF',
'MYX' : 'Mayne Pharma Group Ltd',
'IWLD' : 'Ishares Core MSCI World Ex Aus Esg Leaders ETF',
'WHF' : 'Whitefield Industrials Ltd',
'CBO' : 'Cobram Estate Olives Ltd',
'VVLU' : 'Vanguard Global Value Equity Active ETF (Managed Fund)',
'PFP' : 'Propel Funeral Partners Ltd',
'5EA' : '5E Advanced Materials Inc',
'MIR' : 'Mirrabooka Investments Ltd',
'BCB' : 'Bowen Coking Coal Ltd',
'VG1' : 'Vgi Partners Global Investments Ltd',
'HCW' : 'Healthco Healthcare and Wellness REIT',
'CCX' : 'City Chic Collective Ltd',
'SHV' : 'Select Harvests Ltd',
'OPH' : 'Ophir High Conviction Fund',
'QPON' : 'Betashares Australian Bank Senior Floating Rate Bond ETF',
'QRI' : 'Qualitas Real Estate Income Fund',
'DYL' : 'Deep Yellow Ltd',
'SLF' : 'SPDR S&P/ASX 200 Listed Property Fund',
'VACF' : 'Vanguard Australian Corp Fixed Interest INDEX ETF',
'PGH' : 'Pact Group Holdings Ltd',
'HM1' : 'Hearts and Minds Investments Ltd',
'STX' : 'Strike Energy Ltd',
'IFM' : 'Infomedia Ltd',
'MOT' : 'Metrics Income Opportunities Trust',
'AQZ' : 'Alliance Aviation Services Ltd',
'MHHT' : 'Magellan High Conviction Trust (Managed Fund)',
'STA' : 'Strandline Resources Ltd',
'EQT' : 'EQT Holdings Ltd',
'AGY' : 'Argosy Minerals Ltd',
'GWA' : 'GWA Group Ltd',
'BLX' : 'Beacon Lighting Group Ltd',
'RF1' : 'Regal Investment Fund',
'EHE' : 'Estia Health Ltd',
'WGX' : 'Westgold Resources Ltd',
'ARU' : 'Arafura Resources Ltd',
'LLL' : 'Leo Lithium Ltd',
'RMC' : 'Resimac Group Ltd',
'MGX' : 'Mount Gibson Iron Ltd',
'ACDC' : 'ETFs Battery Tech & Lithium ETF',
'PPC' : 'Peet Ltd',
'PRN' : 'Perenti Global Ltd',
'BENPH' : 'Bendigo and Adelaide Bank Ltd',
'APX' : 'Appen Ltd',
'MNY' : 'MONEY3 Corporation Ltd',
'TIE' : 'Tietto Minerals Ltd',
'ASM' : 'Australian Strategic Materials Ltd',
'SSM' : 'Service Stream Ltd',
'AFG' : 'Australian Finance Group Ltd',
'TYR' : 'Tyro Payments Ltd',
'ILB' : 'Ishares Government Inflation ETF',
'FCL' : 'Fineos Corporation Holdings Plc',
'GDI' : 'GDI Property Group',
'GCI' : 'Gryphon Capital Income Trust',
'VBND' : 'Vanguard Global Aggregate Bond INDEX (Hedged) ETF',
'FGX' : 'Future Generation Investment Company Ltd',
'PLL' : 'Piedmont Lithium Inc',
'PAN' : 'Panoramic Resources Ltd',
'EHL' : 'Emeco Holdings Ltd',
'PGG' : 'Partners Group Global Income Fund',
'OMH' : 'Om Holdings Ltd',
'ADT' : 'Adriatic Metals Plc',
'CGFPB' : 'Challenger Ltd',
'PIC' : 'Perpetual Equity Investment Company Ltd',
'CTM' : 'Centaurus Metals Ltd',
'FGG' : 'Future Generation Global Investment Company Ltd',
'CVW' : 'Clearview Wealth Ltd',
'ILC' : 'Ishares S&P/ASX 20 ETF',
'WBT' : 'Weebit Nano Ltd',
'IJR' : 'Ishares S&P Small-Cap ETF',
'F100' : 'Betashares Ftse 100 ETF',
'PAC' : 'Pacific Current Group Ltd',
'SGLLV' : 'Ricegrowers Ltd',
'MYS' : 'Mystate Ltd',
'ASIA' : 'Betashares Asia Technology Tigers ETF',
'ALI' : 'Argo Global Listed Infrastructure Ltd',
'MNS' : 'Magnis Energy Technologies Ltd',
'PWR' : 'Peter Warren Automotive Holdings Ltd',
'AKP' : 'Audio Pixels Holdings Ltd',
'MOAT' : 'Vaneck Morningstar Wide Moat ETF',
'HT1' : 'HT&E Ltd',
'QHAL' : 'Vaneck MSCI International Quality (Hedged) ETF',
'REP' : 'Ram Essential Services Property Fund',
'CRED' : 'Betashares Australian Investment Grade Corporate Bond ETF',
'HAS' : 'Hastings Technology Metals Ltd',
'ALK' : 'Alkane Resources Ltd',
'PE1' : 'Pengana Private Equity Trust',
'MHJ' : 'Michael Hill International Ltd',
'BVS' : 'Bravura Solutions Ltd',
'RNU' : 'Renascor Resources Ltd',
'TLG' : 'Talga Group Ltd',
'OPT' : 'Opthea Ltd',
'IJP' : 'Ishares MSCI Japan ETF',
'DJRE' : 'SPDR Dow Jones Global Real Estate Esg Fund',
'IAGPD' : 'Insurance Australia Group Ltd',
'VG8' : 'Vgi Partners Asian Investments Ltd',
'MYR' : 'Myer Holdings Ltd',
'BUB' : 'Bubs Australia Ltd',
'ASG' : 'Autosports Group Ltd',
'QOZ' : 'Betashares Ftse Rafi Australia 200 ETF',
'SNL' : 'Supply Network Ltd',
'SKT' : 'Sky Network Television Ltd',
'VETH' : 'Vanguard Ethically Conscious Australian Shares ETF',
'MVF' : 'Monash Ivf Group Ltd',
'BTH' : 'Bigtincan Holdings Ltd',
'JMS' : 'Jupiter Mines Ltd',
'DXC' : 'Dexus Convenience Retail REIT',
'SUNPI' : 'Suncorp Group Ltd',
'PCI' : 'Perpetual Credit Income Trust',
'CGFPC' : 'Challenger Ltd',
'IHL' : 'Incannex Healthcare Ltd',
'GNG' : 'GR Engineering Services Ltd',
'VGL' : 'Vista Group International Ltd',
'SUNPH' : 'Suncorp Group Ltd',
'SKO' : 'Serko Ltd',
'BSE' : 'Base Resources Ltd',
'DVP' : 'Develop Global Ltd',
'FLOT' : 'Vaneck Australian Floating Rate ETF',
'SUNPG' : 'Suncorp Group Ltd',
'AGG' : 'Anglogold Ashanti Ltd',
'KGN' : 'Kogan.com Ltd',
'PMC' : 'Platinum Capital Ltd',
'SSR' : 'SSR Mining Inc',
'GLN' : 'Galan Lithium Ltd',
'GDX' : 'Vaneck Gold Miners ETF',
'SLC' : 'Superloop Ltd',
'CWP' : 'Cedar Woods Properties Ltd',
'MAH' : 'Macmahon Holdings Ltd',
'SST' : 'Steamships Trading Company Ltd',
'ADH' : 'Adairs Ltd',
'UNI' : 'Universal Store Holdings Ltd',
'GEAR' : 'Betashares Geared Australian Equity Fund (Hedge Fund)',
'AGVT' : 'Betashares Australian Government Bond ETF',
'MLD' : 'Maca Ltd',
'SDG' : 'Sunland Group Ltd',
'RUL' : 'Rpmglobal Holdings Ltd',
'A4N' : 'Alpha Hpa Ltd',
'IVE' : 'Ishares MSCI Eafe ETF',
'DDH' : 'DDH1 Ltd',
'RDY' : 'Readytech Holdings Ltd',
'SYM' : 'SYMBIO Holdings Ltd',
'BOQPE' : 'Bank of Queensland Ltd',
'WMI' : 'Wam Microcap Ltd',
'BFG' : 'Bell Financial Group Ltd',
'GDF' : 'Garda Property Group',
'BET' : 'Betmakers Technology Group Ltd',
'BST' : 'Best & Less Group Holdings Ltd',
'HFR' : 'Highfield Resources Ltd',
'GMD' : 'Genesis Minerals Ltd',
'YMAX' : 'Betashares Aus Top 20 Equity Yield MAX Fund (Managed Fund)',
'FZO' : 'Family ZONE Cyber Safety Ltd',
'VAE' : 'Vanguard Ftse Asia Ex Japan Shares INDEX ETF',
'AGX1' : 'Antipodes Global Shares (Quoted Managed Fund)',
'3PL' : '3P Learning Ltd',
'AASF' : 'Airlie Australian Share Fund (Managed Fund)',
'KCN' : 'Kingsgate Consolidated Ltd',
'WDIV' : 'SPDR S&P Global Dividend Fund',
'PAR' : 'Paradigm Biopharmaceuticals Ltd',
'PEB' : 'Pacific Edge Ltd',
'COG' : 'COG Financial Services Ltd',
'AVR' : 'Anteris Technologies Ltd',
'AMH' : 'Amcil Ltd',
'CTT' : 'Cettire Ltd',
'NGI' : 'Navigator Global Investments Ltd',
'AMI' : 'Aurelia Metals Ltd',
'QAU' : 'Betashares Gold Bullion ETF - Currency Hedged',
'EML' : 'EML Payments Ltd',
'AIS' : 'Aeris Resources Ltd',
'RSG' : 'Resolute Mining Ltd',
'SRV' : 'Servcorp Ltd',
'BENPG' : 'Bendigo and Adelaide Bank Ltd',
'SRG' : 'SRG Global Ltd',
'EZL' : 'EUROZ Hartleys Group Ltd',
'PAI' : 'Platinum Asia Investments Ltd',
'TRJ' : 'Trajan Group Holdings Ltd',
'QLTY' : 'Betashares Global Quality Leaders ETF',
'PDI' : 'Predictive Discovery Ltd',
'CDP' : 'Carindale Property Trust',
'CAJ' : 'Capitol Health Ltd',
'VBLD' : 'Vanguard Global Infrastructure INDEX ETF',
'PPE' : 'Peoplein Ltd',
'PPS' : 'Praemium Ltd',
'ECF' : 'Elanor Commercial Property Fund',
'DRE' : 'Dreadnought Resources Ltd',
'IGB' : 'Ishares Treasury ETF',
'GNX' : 'GENEX Power Ltd',
'AYUPA' : 'Australian Unity Ltd',
'NWE' : 'Norwest Energy NL',
'AFP' : 'Aft Pharmaceuticals Ltd',
'AGI' : 'Ainsworth Game Technology Ltd',
'FDV' : 'Frontier Digital Ventures Ltd',
'IGL' : 'Ive Group Ltd',
'RAC' : 'Race Oncology Ltd',
'NWF' : 'Newfield Resources Ltd',
'ISEC' : 'Ishares Enhanced Cash ETF',
'BCK' : 'Brockman Mining Ltd',
'EGG' : 'Enero Group Ltd',
'NPR' : 'Newmark Property REIT'
}
