source_shares = {
"BHP" : "BHP Group Ltd",
"CBA" : "Commonwealth Bank of Australia",
"CSL" : "CSL Ltd",
"NAB" : "National Australia Bank Ltd",
"WBC" : "Westpac Banking Corporation",
"MQG" : "Macquarie Group Ltd",
"WDS" : "Woodside Energy Group Ltd",
"ANZ" : "Australia and New Zealand Banking Group Ltd",
"FMG" : "Fortescue Metals Group Ltd",
"WES" : "Wesfarmers Ltd",
"TLS" : "Telstra Corporation Ltd",
"WOW" : "Woolworths Group Ltd",
"TCL" : "Transurban Group",
"GMG" : "Goodman Group",
"RIO" : "RIO Tinto Ltd",
"STO" : "Santos Ltd",
"COL" : "Coles Group Ltd",
"ALL" : "Aristocrat Leisure Ltd",
"S32" : "SOUTH32 Ltd",
"WTC" : "Wisetech Global Ltd",
"QBE" : "QBE Insurance Group Ltd",
"BXB" : "Brambles Ltd",
"SHL" : "Sonic Healthcare Ltd",
"REA" : "REA Group Ltd",
"RHC" : "Ramsay Health Care Ltd",
"NCM" : "Newcrest Mining Ltd",
"ASX" : "ASX Ltd",
"JHX" : "James Hardie Industries Plc",
"CPU" : "Computershare Ltd",
"SCG" : "Scentre Group",
"COH" : "Cochlear Ltd",
"SUN" : "Suncorp Group Ltd",
"RMD" : "Resmed Inc",
"APA" : "APA Group",
"EDV" : "Endeavour Group Ltd",
"XRO" : "Xero Ltd",
"AMC" : "Amcor Plc",
"MIN" : "Mineral Resources Ltd",
"VAS" : "Vanguard Australian Shares INDEX ETF",
"IAG" : "Insurance Australia Group Ltd",
"ORG" : "Origin Energy Ltd",
"FPH" : "Fisher & Paykel Healthcare Corporation Ltd",
"REH" : "Reece Ltd",
"TPG" : "TPG Telecom Ltd",
"PLS" : "Pilbara Minerals Ltd",
"MPL" : "Medibank Private Ltd",
"AIA" : "Auckland International Airport Ltd",
"TLC" : "The Lottery Corporation Ltd",
"TWE" : "Treasury Wine Estates Ltd",
"MGOC" : "Magellan Global Fund (Open Class) (Managed Fund)",
"IGO" : "IGO Ltd",
"AFI" : "Australian Foundation Investment Company Ltd",
"SOL" : "Washington H Soul Pattinson & Company Ltd",
"DXS" : "Dexus",
"SPK" : "Spark New Zealand Ltd",
"AKE" : "Allkem Ltd",
"NST" : "Northern Star Resources Ltd",
"OZL" : "OZ Minerals Ltd",
"SGP" : "Stockland",
"QAN" : "Qantas Airways Ltd",
"VCX" : "Vicinity Centres",
"MGR" : "Mirvac Group",
"ALD" : "Ampol Ltd",
"PMGOLD" : "Gold Corporation",
"LYC" : "Lynas Rare EARTHS Ltd",
"GPT" : "GPT Group",
"BSL" : "Bluescope Steel Ltd",
"WOR" : "Worley Ltd",
"MCY" : "Mercury NZ Ltd",
"CAR" : "Carsales.com Ltd",
"YAL" : "Yancoal Australia Ltd",
"SEK" : "Seek Ltd",
"ALX" : "Atlas Arteria",
"IPL" : "Incitec Pivot Ltd",
"WHC" : "Whitehaven Coal Ltd",
"IEL" : "Idp Education Ltd",
"ARG" : "Argo Investments Ltd",
"LLC" : "Lendlease Group",
"ORI" : "Orica Ltd",
"AZJ" : "Aurizon Holdings Ltd",
"SVW" : "Seven Group Holdings Ltd",
"EBO" : "Ebos Group Ltd",
"DMP" : "Domino's PIZZA Enterprises Ltd",
"MEZ" : "Meridian Energy Ltd",
"IFT" : "Infratil Ltd",
"CHC" : "Charter Hall Group",
"ALQ" : "Als Ltd",
"CWY" : "Cleanaway Waste Management Ltd",
"HVN" : "Harvey Norman Holdings Ltd",
"PME" : "Pro Medicus Ltd",
"AGL" : "AGL Energy Ltd",
"SDF" : "Steadfast Group Ltd",
"IVV" : "Ishares S&P 500 ETF",
"BEN" : "Bendigo and Adelaide Bank Ltd",
"NXT" : "NEXTDC Ltd",
"ALU" : "Altium Ltd",
"GQG" : "GQG Partners Inc",
"JBH" : "JB Hi-Fi Ltd",
"QUB" : "QUBE Holdings Ltd",
"VGS" : "Vanguard MSCI INDEX International Shares ETF",
"STW" : "SPDR S&P/ASX 200 Fund",
"IOZ" : "Ishares Core S&P/ASX 200 ETF",
"EVN" : "Evolution Mining Ltd",
"AWC" : "Alumina Ltd",
"BOQ" : "Bank of Queensland Ltd",
"CGF" : "Challenger Ltd",
"ILU" : "Iluka Resources Ltd",
"VEA" : "Viva Energy Group Ltd",
"NHC" : "New Hope Corporation Ltd",
"FBU" : "Fletcher Building Ltd",
"MTS" : "Metcash Ltd",
"SQ2" : "Block Inc",
"BPT" : "Beach Energy Ltd",
"TNE" : "Technology One Ltd",
"LTR" : "Liontown Resources Ltd",
"NHF" : "Nib Holdings Ltd",
"AMP" : "AMP Ltd",
"A2M" : "The a2 Milk Company Ltd",
"DOW" : "Downer Edi Ltd",
"FLT" : "Flight Centre Travel Group Ltd",
"ANN" : "Ansell Ltd",
"APE" : "Eagers Automotive Ltd",
"NWL" : "Netwealth Group Ltd",
"NEC" : "Nine Entertainment Co. Holdings Ltd",
"PMV" : "Premier Investments Ltd",
"BLD" : "Boral Ltd",
"CLW" : "Charter Hall Long Wale REIT",
"RWC" : "Reliance Worldwide Corporation Ltd",
"CNU" : "Chorus Ltd",
"BKW" : "Brickworks Ltd",
"CRN" : "Coronado Global Resources Inc",
"CBAPD" : "Commonwealth Bank of Australia",
"APM" : "APM Human Services International Ltd",
"VTS" : "Vanguard US Total Market Shares INDEX ETF",
"BRG" : "Breville Group Ltd",
"SCP" : "Shopping Centres Australasia Property Group",
"SGM" : "Sims Ltd",
"NIC" : "Nickel Industries Ltd",
"ORA" : "Orora Ltd",
"ZIM" : "Zimplats Holdings Ltd",
"NSR" : "National Storage REIT",
"QUAL" : "Vaneck MSCI International Quality ETF",
"GNE" : "Genesis Energy Ltd",
"CIA" : "Champion Iron Ltd",
"AVZ" : "AVZ Minerals Ltd",
"CTD" : "Corporate Travel Management Ltd",
"GOZ" : "Growthpoint Properties Australia",
"SGR" : "The Star Entertainment Group Ltd",
"HDN" : "Homeco Daily Needs REIT",
"BWP" : "BWP Trust",
"GOLD" : "ETFs Metal Securities Australia Ltd",
"IOO" : "Ishares Global 100 ETF",
"PXA" : "Pexa Group Ltd",
"ARB" : "ARB Corporation Ltd",
"NDQ" : "Betashares Nasdaq 100 ETF",
"EVT" : "Event Hospitality and Entertainment Ltd",
"NABPH" : "National Australia Bank Ltd",
"MFG" : "Magellan Financial Group Ltd",
"CXO" : "Core Lithium Ltd",
"DRR" : "Deterra Royalties Ltd",
"SYA" : "Sayona Mining Ltd",
"ABP" : "Abacus Property Group",
"SNZ" : "Summerset Group Holdings Ltd",
"CQR" : "Charter Hall Retail REIT",
"VNT" : "Ventia Services Group Ltd",
"SUL" : "Super Retail Group Ltd",
"VHY" : "Vanguard Australian Shares High Yield ETF",
"A200" : "Betashares Australia 200 ETF",
"BFL" : "BSP Financial Group Ltd",
"BAP" : "Bapcor Ltd",
"CSR" : "CSR Ltd",
"LNK" : "Link Administration Holdings Ltd",
"PRU" : "Perseus Mining Ltd",
"PDN" : "Paladin Energy Ltd",
"DHG" : "Domain Holdings Australia Ltd",
"VEU" : "Vanguard All-World Ex-US Shares INDEX ETF",
"HLS" : "Healius Ltd",
"VAP" : "Vanguard Australian Property Securities INDEX ETF",
"SMR" : "Stanmore Resources Ltd",
"PNI" : "Pinnacle Investment Management Group Ltd",
"TAH" : "Tabcorp Holdings Ltd",
"MGF" : "Magellan Global Fund",
"IPH" : "IPH Ltd",
"ETHI" : "Betashares Global Sustainability Leaders ETF",
"IRE" : "Iress Ltd",
"IFL" : "Insignia Financial Ltd",
"CMW" : "Cromwell Property Group",
"HUB" : "HUB24 Ltd",
"SKC" : "Skycity Entertainment Group Ltd",
"TLX" : "TELIX Pharmaceuticals Ltd",
"AIZ" : "Air New Zealand Ltd",
"DDR" : "Dicker Data Ltd",
"NABPI" : "National Australia Bank Ltd",
"LOV" : "Lovisa Holdings Ltd",
"AUB" : "AUB Group Ltd",
"VUK" : "Virgin Money Uk Plc",
"WAM" : "WAM Capital Ltd",
"SFR" : "Sandfire Resources Ltd",
"NABPF" : "National Australia Bank Ltd",
"JLG" : "Johns LYNG Group Ltd",
"NUF" : "Nufarm Ltd",
"WEB" : "Webjet Ltd",
"HYGG" : "Hyperion GBL Growth Companies Fund (Managed Fund)",
"INA" : "Ingenia Communities Group",
"CIP" : "Centuria Industrial REIT",
"GNC" : "Graincorp Ltd",
"PDL" : "Pendal Group Ltd",
"HBRD" : "Betashares Active Australian Hybrids Fund (Managed Fund)",
"AAA" : "Betashares Australian High Interest Cash ETF",
"WPR" : "Waypoint REIT",
"ELD" : "Elders Ltd",
"VGAD" : "Vanguard MSCI INDEX International Shares (Hedged) ETF",
"LIC" : "Lifestyle Communities Ltd",
"WBCPJ" : "Westpac Banking Corporation",
"VDHG" : "Vanguard Diversified High Growth INDEX ETF",
"WBCPK" : "Westpac Banking Corporation",
"MXT" : "Metrics Master Income Trust",
"CEN" : "Contact Energy Ltd",
"CBAPK" : "Commonwealth Bank of Australia",
"WBCPH" : "Westpac Banking Corporation",
"PPT" : "Perpetual Ltd",
"IAF" : "Ishares Core Composite Bond ETF",
"LKE" : "Lake Resources N.L.",
"ANZPG" : "Australia and New Zealand Banking Group Ltd",
"MVW" : "Vaneck Australian EQUAL Weight ETF",
"PSI" : "PSC Insurance Group Ltd",
"CBAPI" : "Commonwealth Bank of Australia",
"CBAPH" : "Commonwealth Bank of Australia",
"GRR" : "Grange Resources Ltd",
"CHN" : "Chalice Mining Ltd",
"BRN" : "Brainchip Holdings Ltd",
"OCL" : "Objective Corporation Ltd",
"IVC" : "Invocare Ltd",
"WLE" : "Wam Leaders Ltd",
"HMC" : "Home Consortium Ltd",
"RBD" : "Restaurant Brands New Zealand Ltd",
"WBCPL" : "Westpac Banking Corporation",
"LSF" : "L1 Long Short Fund Ltd",
"MAQ" : "Macquarie Telecom Group Ltd",
"ANZPI" : "Australia and New Zealand Banking Group Ltd",
"LFS" : "Latitude Group Holdings Ltd",
"NABPD" : "National Australia Bank Ltd",
"MFF" : "MFF Capital Investments Ltd",
"ARF" : "Arena REIT",
"WBCPI" : "Westpac Banking Corporation",
"CNI" : "Centuria Capital Group",
"IMU" : "Imugene Ltd",
"ABC" : "Adbri Ltd",
"CMM" : "Capricorn Metals Ltd",
"VAF" : "Vanguard Australian Fixed Interest INDEX ETF",
"INR" : "Ioneer Ltd",
"GOR" : "Gold Road Resources Ltd",
"CBAPG" : "Commonwealth Bank of Australia",
"KLS" : "Kelsian Group Ltd",
"WAF" : "West African Resources Ltd",
"LFG" : "Liberty Financial Group",
"CCP" : "Credit Corp Group Ltd",
"CQE" : "Charter Hall Social Infrastructure REIT",
"JDO" : "Judo Capital Holdings Ltd",
"PPH" : "Pushpay Holdings Ltd",
"BKL" : "Blackmores Ltd",
"NAN" : "Nanosonics Ltd",
"DEG" : "De Grey Mining Ltd",
"PNV" : "Polynovo Ltd",
"CDA" : "Codan Ltd",
"RCAP" : "Resolution Cap Global Prop Sec (Managed Fund)",
"ANZPJ" : "Australia and New Zealand Banking Group Ltd",
"BKI" : "BKI Investment Company Ltd",
"MP1" : "Megaport Ltd",
"CGC" : "Costa Group Holdings Ltd",
"MGH" : "Maas Group Holdings Ltd",
"SLR" : "Silver Lake Resources Ltd",
"FAIR" : "Betashares Australian Sustainability Leaders ETF",
"AUI" : "Australian United Investment Company Ltd",
"GUD" : "G.U.D. Holdings Ltd",
"RRL" : "Regis Resources Ltd",
"CBAPJ" : "Commonwealth Bank of Australia",
"MND" : "Monadelphous Group Ltd",
"SP1" : "Southern Cross Payments Ltd",
"OBL" : "Omni Bridgeway Ltd",
"VUL" : "Vulcan Energy Resources Ltd",
"NVX" : "Novonix Ltd",
"CKF" : "Collins Foods Ltd",
"IXJ" : "Ishares Global Healthcare ETF",
"CXL" : "CALIX Ltd",
"BGP" : "Briscoe Group Australasia Ltd",
"TGR" : "Tassal Group Ltd",
"BGA" : "Bega Cheese Ltd",
"AAC" : "Australian Agricultural Company Ltd",
"NWS" : "News Corporation",
"GMA" : "Genworth Mortgage Insurance Australia Ltd",
"NEA" : "Nearmap Ltd",
"VSL" : "Vulcan Steel Ltd",
"DBI" : "Dalrymple Bay Infrastructure Ltd",
"MAF" : "Ma Financial Group Ltd",
"PBH" : "Pointsbet Holdings Ltd",
"PTM" : "Platinum Asset Management Ltd",
"KAR" : "Karoon Energy Ltd",
"SYR" : "Syrah Resources Ltd",
"NWH" : "NRW Holdings Ltd"
}
