INSERT INTO Share (Ticker, Name) VALUES ('A200','Betashares Australia 200 ETF')
INSERT INTO Share (Ticker, Name) VALUES ('A2M','The a2 Milk Company Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('AAA','Betashares Australian High Interest Cash ETF')
INSERT INTO Share (Ticker, Name) VALUES ('ABC','Adbri Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ABP','Abacus Property Group')
INSERT INTO Share (Ticker, Name) VALUES ('AFI','Australian Foundation Investment Company Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('AGL','AGL Energy Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('AIA','Auckland International Airport Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('AIZ','Air New Zealand Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ALD','Ampol Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ALL','Aristocrat Leisure Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ALQ','Als Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ALU','Altium Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ALX','Atlas Arteria')
INSERT INTO Share (Ticker, Name) VALUES ('AMC','Amcor Plc')
INSERT INTO Share (Ticker, Name) VALUES ('AMP','AMP Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ANN','Ansell Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ANZ','Australia and New Zealand Banking Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('APA','APA Group')
INSERT INTO Share (Ticker, Name) VALUES ('APE','Eagers Automotive Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('APT','Afterpay Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('APX','Appen Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ARB','ARB Corporation Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ARF','Arena REIT')
INSERT INTO Share (Ticker, Name) VALUES ('ARG','Argo Investments Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('AST','Ausnet Services Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ASX','ASX Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('AUB','AUB Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('AUI','Australian United Investment Company Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('AVN','Aventus Group')
INSERT INTO Share (Ticker, Name) VALUES ('AWC','Alumina Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('AX1','Accent Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('AZJ','Aurizon Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BAP','Bapcor Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BEN','Bendigo and Adelaide Bank Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BET','Betmakers Technology Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BGA','Bega Cheese Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BHP','BHP Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BIN','Bingo Industries Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BKI','BKI Investment Company Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BKL','Blackmores Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BKW','Brickworks Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BLD','Boral Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BOQ','Bank of Queensland Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BPT','Beach Energy Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BRG','Breville Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BRN','Brainchip Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BSL','Bluescope Steel Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('BWP','BWP Trust')
INSERT INTO Share (Ticker, Name) VALUES ('BXB','Brambles Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CAR','Carsales.com Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CBA','Commonwealth Bank of Australia')
INSERT INTO Share (Ticker, Name) VALUES ('CCL','Coca-Cola Amatil LtdSuspended')
INSERT INTO Share (Ticker, Name) VALUES ('CCP','Credit Corp Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CCX','City Chic Collective Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CDA','Codan Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CEN','Contact Energy Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CGC','Costa Group Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CGF','Challenger Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CHC','Charter Hall Group')
INSERT INTO Share (Ticker, Name) VALUES ('CHN','Chalice Mining Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CIA','Champion Iron Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CIM','Cimic Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CIP','Centuria Industrial REIT')
INSERT INTO Share (Ticker, Name) VALUES ('CKF','Collins Foods Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CLW','Charter Hall Long Wale REIT')
INSERT INTO Share (Ticker, Name) VALUES ('CMW','Cromwell Property Group')
INSERT INTO Share (Ticker, Name) VALUES ('CNI','Centuria Capital Group')
INSERT INTO Share (Ticker, Name) VALUES ('CNU','Chorus Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('COF','Centuria Office REIT')
INSERT INTO Share (Ticker, Name) VALUES ('COH','Cochlear Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('COL','Coles Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CPU','Computershare Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CQE','Charter Hall Social Infrastructure REIT')
INSERT INTO Share (Ticker, Name) VALUES ('CQR','Charter Hall Retail REIT')
INSERT INTO Share (Ticker, Name) VALUES ('CRN','Coronado Global Resources Inc')
INSERT INTO Share (Ticker, Name) VALUES ('CSL','CSL Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CSR','CSR Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CTD','Corporate Travel Management Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CUV','Clinuvel Pharmaceuticals Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CWN','Crown Resorts Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('CWY','Cleanaway Waste Management Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('DBI','Dalrymple Bay Infrastructure Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('DDR','Dicker Data Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('DEG','De Grey Mining Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('DHG','Domain Holdings Australia Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('DMP',"Domino's PIZZA Enterprises Ltd")
INSERT INTO Share (Ticker, Name) VALUES ('DOW','Downer Edi Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('DRR','Deterra Royalties Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('DTL','Data#3 Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('DUI','Diversified United Investment Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('DXS','Dexus')
INSERT INTO Share (Ticker, Name) VALUES ('EBO','Ebos Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ELD','Elders Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('EML','EML Payments Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ETHI','Betashares Global Sustainability Leaders ETF')
INSERT INTO Share (Ticker, Name) VALUES ('EVN','Evolution Mining Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('EVT','Event Hospitality and Entertainment Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('FAIR','Betashares Australian Sustainability Leaders ETF')
INSERT INTO Share (Ticker, Name) VALUES ('FBU','Fletcher Building Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('FCL','Fineos Corporation Holdings Plc')
INSERT INTO Share (Ticker, Name) VALUES ('FLT','Flight Centre Travel Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('FMG','Fortescue Metals Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('FPH','Fisher & Paykel Healthcare Corporation Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('GMA','Genworth Mortgage Insurance Australia Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('GMG','Goodman Group')
INSERT INTO Share (Ticker, Name) VALUES ('GNC','Graincorp Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('GNE','Genesis Energy Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('GOLD','ETFs Metal Securities Australia Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('GOR','Gold Road Resources Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('GOZ','Growthpoint Properties Australia')
INSERT INTO Share (Ticker, Name) VALUES ('GPT','GPT Group')
INSERT INTO Share (Ticker, Name) VALUES ('GUD','G.U.D. Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('GXY','Galaxy Resources Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('HBRD','Betashares Active Australian Hybrids Fund (Managed Fund)')
INSERT INTO Share (Ticker, Name) VALUES ('HGH','Heartland Group Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('HLS','Healius Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('HM1','Hearts and Minds Investments Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('HMC','Home Consortium')
INSERT INTO Share (Ticker, Name) VALUES ('HSN','Hansen Technologies Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('HTA','Hutchison Telecommunications (Australia) Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('HUB','HUB24 Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('HVN','Harvey Norman Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('HYGG','Hyperion GBL Growth Companies Fund (Managed Fund)')
INSERT INTO Share (Ticker, Name) VALUES ('IAF','Ishares Core Composite Bond ETF')
INSERT INTO Share (Ticker, Name) VALUES ('IAG','Insurance Australia Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('IDX','Integral Diagnostics Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('IEL','Idp Education Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('IEM','Ishares MSCI Emerging Markets ETF')
INSERT INTO Share (Ticker, Name) VALUES ('IFL','IOOF Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('IFT','Infratil Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('IGO','IGO Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ILU','Iluka Resources Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('INA','Ingenia Communities Group')
INSERT INTO Share (Ticker, Name) VALUES ('ING','Inghams Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('IOO','Ishares Global 100 ETF')
INSERT INTO Share (Ticker, Name) VALUES ('IOZ','Ishares Core S&P/ASX 200 ETF')
INSERT INTO Share (Ticker, Name) VALUES ('IPH','IPH Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('IPL','Incitec Pivot Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('IRE','Iress Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ISX','Isignthis LtdSuspended')
INSERT INTO Share (Ticker, Name) VALUES ('IVC','Invocare Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('IVV','Ishares S&P 500 ETF')
INSERT INTO Share (Ticker, Name) VALUES ('JBH','JB Hi-Fi Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('JHG','Janus Henderson Group Plc')
INSERT INTO Share (Ticker, Name) VALUES ('JHX','James Hardie Industries Plc')
INSERT INTO Share (Ticker, Name) VALUES ('KGN','Kogan.com Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('LEP','Ale Property Group')
INSERT INTO Share (Ticker, Name) VALUES ('LFG','Liberty Financial Group')
INSERT INTO Share (Ticker, Name) VALUES ('LFS','Latitude Group Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('LIC','Lifestyle Communities Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('LLC','Lendlease Group')
INSERT INTO Share (Ticker, Name) VALUES ('LNK','Link Administration Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('LOV','Lovisa Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('LSF','L1 Long Short Fund Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('LYC','Lynas Rare EARTHS Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MAQ','Macquarie Telecom Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MCY','Mercury NZ Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MEZ','Meridian Energy Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MFF','MFF Capital Investments Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MFG','Magellan Financial Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MGF','Magellan Global Fund')
INSERT INTO Share (Ticker, Name) VALUES ('MGH','Maas Group Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MGOC','Magellan Global Fund (Open Class) (Managed Fund)')
INSERT INTO Share (Ticker, Name) VALUES ('MGR','Mirvac Group')
INSERT INTO Share (Ticker, Name) VALUES ('MGX','Mount Gibson Iron Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MIN','Mineral Resources Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MLT','Milton Corporation Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MND','Monadelphous Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MP1','Megaport Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MPL','Medibank Private Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MQG','Macquarie Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MSB','Mesoblast Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MTS','Metcash Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('MVW','Vaneck Vectors Australian EQUAL Weight ETF')
INSERT INTO Share (Ticker, Name) VALUES ('MXT','MCP Master Income Trust')
INSERT INTO Share (Ticker, Name) VALUES ('NAB','National Australia Bank Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NAN','Nanosonics Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NCM','Newcrest Mining Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NDQ','Betashares Nasdaq 100 ETF')
INSERT INTO Share (Ticker, Name) VALUES ('NEA','Nearmap Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NEC','Nine Entertainment Co. Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NHC','New Hope Corporation Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NHF','Nib Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NIC','Nickel Mines Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NSR','National Storage REIT')
INSERT INTO Share (Ticker, Name) VALUES ('NST','Northern Star Resources Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NUF','Nufarm Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NWH','NRW Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NWL','Netwealth Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NWS','News Corporation')
INSERT INTO Share (Ticker, Name) VALUES ('NXL','NUIX Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('NXT','NEXTDC Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('OBL','Omni Bridgeway Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('OCL','Objective Corporation Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('OML','Ooh!Media Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ORA','Orora Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ORE','Orocobre Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ORG','Origin Energy Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ORI','Orica Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('OSH','Oil Search Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('OZL','OZ Minerals Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PBH','Pointsbet Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PDL','Pendal Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PDN','Paladin Energy Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PGH','Pact Group Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PLL','Piedmont Lithium Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PLS','Pilbara Minerals Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PME','Pro Medicus Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PMGOLD','Gold')
INSERT INTO Share (Ticker, Name) VALUES ('PMV','Premier Investments Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PNI','Pinnacle Investment Management Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PNV','Polynovo Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PPH','Pushpay Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PPT','Perpetual Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PRU','Perseus Mining Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PSI','PSC Insurance Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('PTM','Platinum Asset Management Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('QAN','Qantas Airways Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('QBE','QBE Insurance Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('QUAL','Vaneck Vectors MSCI World Ex Australia Quality ETF')
INSERT INTO Share (Ticker, Name) VALUES ('QUB','QUBE Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('RBD','Restaurant Brands New Zealand Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('RBL','Redbubble Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('REA','REA Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('REH','Reece Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('RHC','Ramsay Health Care Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('RIO','RIO Tinto Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('RMC','Resimac Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('RMD','Resmed Inc')
INSERT INTO Share (Ticker, Name) VALUES ('RMS','Ramelius Resources Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('RRL','Regis Resources Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('RWC','Reliance Worldwide Corporation Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('S32','SOUTH32 Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SBM','ST Barbara Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SCG','Scentre Group')
INSERT INTO Share (Ticker, Name) VALUES ('SCP','Shopping Centres Australasia Property Group')
INSERT INTO Share (Ticker, Name) VALUES ('SDF','Steadfast Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SEK','Seek Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SFR','Sandfire Resources Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SGM','Sims Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SGP','Stockland')
INSERT INTO Share (Ticker, Name) VALUES ('SGR','The Star Entertainment Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SHL','Sonic Healthcare Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SIQ','Smartgroup Corporation Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SKC','Skycity Entertainment Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SKI','Spark Infrastructure Group')
INSERT INTO Share (Ticker, Name) VALUES ('SLK','Sealink Travel Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SLR','Silver Lake Resources Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SNZ','Summerset Group Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SOL','Washington H Soul Pattinson & Company Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SPK','Spark New Zealand Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('STO','Santos Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('STW','SPDR S&P/ASX 200 Fund')
INSERT INTO Share (Ticker, Name) VALUES ('SUL','Super Retail Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SUN','Suncorp Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SVW','Seven Group Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('SYD','Sydney Airport')
INSERT INTO Share (Ticker, Name) VALUES ('TAH','Tabcorp Holdings Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('TCL','Transurban Group')
INSERT INTO Share (Ticker, Name) VALUES ('TLS','Telstra Corporation Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('TLT','Tilt Renewables Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('TLX','TELIX Pharmaceuticals Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('TNE','Technology One Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('TPG','TPG Telecom Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('TPW','Temple & Webster Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('TWE','Treasury Wine Estates Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('TYR','Tyro Payments Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('UMG','United Malt Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('URW','Unibail-Rodamco-Westfield')
INSERT INTO Share (Ticker, Name) VALUES ('UWL','Uniti Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('VAF','Vanguard Australian Fixed Interest INDEX ETF')
INSERT INTO Share (Ticker, Name) VALUES ('VAP','Vanguard Australian Property Securities INDEX ETF')
INSERT INTO Share (Ticker, Name) VALUES ('VAS','Vanguard Australian Shares INDEX ETF')
INSERT INTO Share (Ticker, Name) VALUES ('VCX','Vicinity Centres')
INSERT INTO Share (Ticker, Name) VALUES ('VEA','Viva Energy Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('VEU','Vanguard All-World Ex-US Shares INDEX ETF')
INSERT INTO Share (Ticker, Name) VALUES ('VGAD','Vanguard MSCI INDEX International Shares (Hedged) ETF')
INSERT INTO Share (Ticker, Name) VALUES ('VGS','Vanguard MSCI INDEX International Shares ETF')
INSERT INTO Share (Ticker, Name) VALUES ('VHY','Vanguard Australian Shares High Yield ETF')
INSERT INTO Share (Ticker, Name) VALUES ('VOC','Vocus Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('VTS','Vanguard US Total Market Shares INDEX ETF')
INSERT INTO Share (Ticker, Name) VALUES ('VUK','Virgin Money Uk Plc')
INSERT INTO Share (Ticker, Name) VALUES ('WAM','WAM Capital Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('WBC','Westpac Banking Corporation')
INSERT INTO Share (Ticker, Name) VALUES ('WEB','Webjet Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('WES','Wesfarmers Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('WGX','Westgold Resources Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('WHC','Whitehaven Coal Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('WLE','Wam Leaders Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('WOR','Worley Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('WOW','Woolworths Group Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('WPL','Woodside Petroleum Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('WPR','Waypoint REIT')
INSERT INTO Share (Ticker, Name) VALUES ('WTC','Wisetech Global Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('XRO','Xero Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('YAL','Yancoal Australia Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('Z1P','ZIP Co Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ZEL','Z Energy Ltd')
INSERT INTO Share (Ticker, Name) VALUES ('ZIM','Zimplats Holdings Ltd')